[INFO] [launch]: All log files can be found below /home/neko/.ros/log/2024-01-26-04-37-33-587231-nekobus-3526
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ydlidar_ros2_driver_node-1]: process started with pid [3555]
[INFO] [controller_lazer-4]: process started with pid [3561]
[INFO] [static_transform_publisher-2]: process started with pid [3557]
[INFO] [servo-3]: process started with pid [3559]
[INFO] [rviz2-5]: process started with pid [3563]
[static_transform_publisher-2] [WARN] []: Old-style arguments are deprecated; see --help for new-style arguments
[rviz2-5] qt.qpa.xcb: could not connect to display 
[rviz2-5] qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
[rviz2-5] This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
[rviz2-5] 
[rviz2-5] Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
[rviz2-5] 
[ydlidar_ros2_driver_node-1] [0m[INFO] [ydlidar_ros2_driver_node]: [YDLIDAR INFO] Current ROS Driver Version: 1.0.1
[ydlidar_ros2_driver_node-1] [0m
[ydlidar_ros2_driver_node-1] [YDLIDAR] SDK initializing
[ydlidar_ros2_driver_node-1] [YDLIDAR] SDK has been initialized
[ydlidar_ros2_driver_node-1] [YDLIDAR] SDK Version: 1.1.21
[static_transform_publisher-2] [INFO] [static_tf_pub_laser]: Spinning until stopped - publishing transform
[static_transform_publisher-2] translation: ('0.000000', '0.000000', '0.020000')
[static_transform_publisher-2] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
[static_transform_publisher-2] from 'base_link' to 'laser_frame'
[ydlidar_ros2_driver_node-1] [YDLIDAR] Lidar successfully connected [/dev/ttyUSB0:115200]
[controller_lazer-4] Traceback (most recent call last):
[controller_lazer-4]   File "/home/neko/Documents/Car/ydlidar_ros2_ws/install/rpi_robot_py/lib/rpi_robot_py/controller_lazer", line 33, in <module>
[controller_lazer-4]     sys.exit(load_entry_point('rpi-robot-py==0.0.0', 'console_scripts', 'controller_lazer')())
[controller_lazer-4]   File "/home/neko/Documents/Car/ydlidar_ros2_ws/install/rpi_robot_py/lib/rpi_robot_py/controller_lazer", line 25, in importlib_load_entry_point
[controller_lazer-4]     return next(matches).load()
[controller_lazer-4]   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 173, in load
[controller_lazer-4]     return functools.reduce(getattr, attrs, module)
[controller_lazer-4] AttributeError: module 'rpi_robot_py.controller_lazer' has no attribute 'main'
[ERROR] [controller_lazer-4]: process has died [pid 3561, exit code 1, cmd '/home/neko/Documents/Car/ydlidar_ros2_ws/install/rpi_robot_py/lib/rpi_robot_py/controller_lazer --ros-args --params-file /home/neko/Documents/Car/ydlidar_ros2_ws/src/rpi_robot_py/params/controller_075_0.yaml'].
[ydlidar_ros2_driver_node-1] [YDLIDAR] Lidar running correctly! The health status: good
[ydlidar_ros2_driver_node-1] [YDLIDAR] Lidar init success, Elapsed time 652 ms
[ydlidar_ros2_driver_node-1] [YDLIDAR] Fail to get baseplate device information
[ydlidar_ros2_driver_node-1] [YDLIDAR] Start to getting intensity flag
[ERROR] [rviz2-5]: process has died [pid 3563, exit code -6, cmd '/opt/ros/humble/lib/rviz2/rviz2 -d /home/neko/Documents/Car/ydlidar_ros2_ws/install/ydlidar_ros2_driver/share/ydlidar_ros2_driver/config/ydlidar.rviz --ros-args -r __node:=rviz2'].
[ydlidar_ros2_driver_node-1] [YDLIDAR] Auto set intensity 0
[ydlidar_ros2_driver_node-1] [YDLIDAR] End to getting intensity flag
[ydlidar_ros2_driver_node-1] [YDLIDAR] Create thread 0x63FFE8E0
[ydlidar_ros2_driver_node-1] [YDLIDAR] Successed to start scan mode, Elapsed time 2812 ms
[ydlidar_ros2_driver_node-1] [YDLIDAR] Fixed Size: 720
[ydlidar_ros2_driver_node-1] [YDLIDAR] Sample Rate: 3.00K
[ydlidar_ros2_driver_node-1] [YDLIDAR] Fixed Size: 720
[ydlidar_ros2_driver_node-1] [YDLIDAR] Sample Rate: 3.00K
[ydlidar_ros2_driver_node-1] [YDLIDAR] Fixed Size: 720
[ydlidar_ros2_driver_node-1] [YDLIDAR] Sample Rate: 3.00K
[ydlidar_ros2_driver_node-1] [YDLIDAR] Single Fixed Size: 260
[ydlidar_ros2_driver_node-1] [YDLIDAR] Sample Rate: 3.00K
[ydlidar_ros2_driver_node-1] [YDLIDAR] Successed to check the lidar, Elapsed time 340 ms
[ydlidar_ros2_driver_node-1] [YDLIDAR] Now lidar is scanning...
[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[static_transform_publisher-2] [INFO] [rclcpp]: signal_handler(signum=2)
[INFO] [static_transform_publisher-2]: process has finished cleanly [pid 3557]
[ERROR] [servo-3]: process has died [pid 3559, exit code 1, cmd '/home/neko/Documents/Car/ydlidar_ros2_ws/install/rpi_robot_py/lib/rpi_robot_py/servo --ros-args'].
[ydlidar_ros2_driver_node-1] [0m[INFO] [rclcpp]: signal_handler(signum=2)[0m
[ydlidar_ros2_driver_node-1] [0m[INFO] [ydlidar_ros2_driver_node]: [YDLIDAR INFO] Now YDLIDAR is stopping .......[0m
[ydlidar_ros2_driver_node-1] [YDLIDAR DEBUG] Thread [0x63FFE8E0] ready to cancel[0]
[ydlidar_ros2_driver_node-1] [YDLIDAR DEBUG] Thread [0x63FFE8E0] ready to cancel[0] time[4]
[ydlidar_ros2_driver_node-1] [YDLIDAR] Thread [0x63FFE8E0] has been canceled
[ydlidar_ros2_driver_node-1] [YDLIDAR] Now lidar scanning has stopped!
[servo-3] Traceback (most recent call last):
[servo-3]   File "/home/neko/Documents/Car/ydlidar_ros2_ws/install/rpi_robot_py/lib/rpi_robot_py/servo", line 33, in <module>
[servo-3]     sys.exit(load_entry_point('rpi-robot-py==0.0.0', 'console_scripts', 'servo')())
[servo-3]   File "/home/neko/Documents/Car/ydlidar_ros2_ws/install/rpi_robot_py/lib/python3.10/site-packages/rpi_robot_py/output_servo.py", line 85, in main
[servo-3]     rclpy.shutdown()
[servo-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 126, in shutdown
[servo-3]     _shutdown(context=context)
[servo-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/utilities.py", line 58, in shutdown
[servo-3]     return context.shutdown()
[servo-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/context.py", line 102, in shutdown
[servo-3]     self.__context.shutdown()
[servo-3] rclpy._rclpy_pybind11.RCLError: failed to shutdown: rcl_shutdown already called on the given context, at ./src/rcl/init.c:241
[INFO] [ydlidar_ros2_driver_node-1]: process has finished cleanly [pid 3555]
